config/routes.rb
Djwebsite::Application.routes.draw do

  get "aboutus/index"

  get "testimonials/index"

  get "contactus/index"

  get "ournights/index"

  get "biography/index"

  get "enquires/index"

  get "events/index"

  get "events/new"

  get "events/update"

  get "events/create"

  get "events/delete"

  get "events/show"

  get "new/update"

  get "new/create"

  get "new/delete"

  get "new/show"

  get "user_sessions/new"
  
  get "home/v1"

  resources :news
  
  resources :events

get "enquies/index"

post "enquires/new"

  resource :user_session
  resources :users
  

  root :to => 'home#index'

	match "/"  => "home#index", :as => "home"
	match "/login" => "user_sessions#new", :as => 'login'
	match "/logout" => "user_sessions#destroy", :as => "logout"
	match '/users/new?code=' => 'users#new'
  match "/404", :to => "error_templates#error_404"

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :title, :description, :event_date
  
  validates_presence_of :title, :description, :event_date
  
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    
  before_filter :authenticate
  skip_before_filter :authenticate, :only => ['index', 'show']
  
  def index
@events = Event.find(:all, :order => "event_date ASC", :limit => 3)
	
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  def new
	@events = Event.new
	
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  def edit
	@events = Event.find(params[:id])
  end

  def create
    @events = Event.new(params[:event])
	#@events.user_id = current_user.id
    respond_to do |format|
      if @events.save
        format.html { redirect_to @events, notice: 'Events was successfully created.' }
        format.json { render json: @events, status: :created, location: @events }
      else
        format.html { render :action => "new" }
        format.json { render json: @events.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update
    @events = Event.find(params[:id])

    respond_to do |format|
      if @events.update_attributes(params[:event])
        format.html { redirect_to @events, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @events.errors, status: :unprocessable_entity }
      end
    end
end

  def destroy
      @events = Event.find(params[:id])
    @events.destroy

    respond_to do |format|
      format.html { redirect_to events_index_url }
      format.json { head :no_content }
    end
  end

  def show
	  @event = Event.find(params[:id])
	
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<% content_for :event_date do %>
  <%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.17/themes/redmond/jquery-ui.css" %>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.17/jquery-ui.min.js", "application" %>
<% end %>
 
 <%= form_for(@events, :html => { :multipart => true }) do |f| %>
  <% if @events.errors.any? %>
	<div id="EditShowErrorLocation">
	    <div id="error_explanation">
	      <h6>There is <%= pluralize(@events.errors.count, "error(s)") %> prohibiting this event from being created:</h6>
	      <ul>
		      <% @events.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		      <% end %>
	      </ul>
	    </div>
	</div>	
  <% end %>
	<table id="TableEventsContent">
		<tr>
			<th>
				<%= f.label :title %>
			</th>
			<td>
				<%= f.text_field :title, :size=>"130x10" %>
			</td>
		</tr>
		<tr>
			<th>
				<%= f.label :description, "Details" %>
			</th>
			<td>
				<%= f.text_area :description, :size=>"100x10" %>
			</td>
		</tr>
		<tr>
			<th>
				<%= f.label :event_date, "Date" %>
			</th>
			<td>
				<%= f.text_field :event_date, :size=>"15" %>
			</td>
		</tr>
		<tr>
			<td style="border-style:none">
			</td>
			<td style="text-align:right; border-style:none">
				<%= f.submit %>
			</td>
		</tr>
	</table>
<% end %>

app/views/events/edit.html.erb
<h1>
	Editing: <%= @events.title %>
</h1>
<%= render 'form' %>

app/views/events/index.html.erb
<h1>Events: Past, Present, Future</h1>
<p>View the schedule!</p>
	<% @events.each do |event| %>
		<div id="indexContents">
			<div id="indexContentTitle">
				<%= link_to event.title, event_path(event) %>
			</div>
			<div id="indexContentContent">
				<%= event.description %>
				<span id="eventTime">
					<%= event.event_date.to_s() %>
				</span>
				<% if isAdmin %>
					<br />
					<%= link_to 'Edit '+event.title, edit_event_path(event) %>
					<%= button_to 'Delete', event_path(event), :method => 'delete' %>
				<% end %>
			</div>
			<br />
		</div>
	<% end %>
	<br />
<% if isAdmin %>
	<%= link_to "Create New Event", :action=>"new" %>
<% end %>

app/views/events/new.html.erb
<h1>Create a new event</h1>

<%= render "form" %>

app/views/events/show.html.erb
<h1>Showing Event:</h1>
<div id="indexContents">
	<div id="indexContentTitle">
		<%= link_to @event.title, event_path(@event) %>
	</div>
	<div id="indexContentContent">
		<%= @event.description %>
		<span id="eventTime">
			<%= @event.event_date.to_s() %>
		</span>
		<% if isAdmin %>
			<%= link_to 'Edit', edit_event_path(@event) %>
		<% end %>
	</div>
</div>
<%= link_to 'View Other Events', events_path %>