config/routes.rb
Djwebsite::Application.routes.draw do

  get "aboutus/index"

  get "testimonials/index"

  get "contactus/index"

  get "ournights/index"

  get "biography/index"

  get "enquires/index"

  get "events/index"

  get "events/new"

  get "events/update"

  get "events/create"

  get "events/delete"

  get "events/show"

  get "new/update"

  get "new/create"

  get "new/delete"

  get "new/show"

  get "user_sessions/new"
  
  get "home/v1"

  resources :news
  
  resources :events

get "enquies/index"

post "enquires/new"

  resource :user_session
  resources :users
  

  root :to => 'home#index'

	match "/"  => "home#index", :as => "home"
	match "/login" => "user_sessions#new", :as => 'login'
	match "/logout" => "user_sessions#destroy", :as => "logout"
	match '/users/new?code=' => 'users#new'
  match "/404", :to => "error_templates#error_404"

end

app/models/news.rb
class News < ActiveRecord::Base
  attr_accessible :content, :title
  
  validates_presence_of :title, :content
  
	def self.user_id
		user_id = current_user.id
	end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  # GET /news
  # GET /news.json
  
  before_filter :authenticate
  skip_before_filter :authenticate, :only => ['index', 'show']
  
  def index
    @news = News.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1
  # GET /news/1.json
  def show
    @news = News.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/new
  # GET /news/new.json
  def new
    @news = News.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1/edit
  def edit
    @news = News.find(params[:id])
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(params[:news])
	@news.user_id = 1
    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render json: @news, status: :created, location: @news }
      else
        format.html { render action: "new" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /news/1
  # PUT /news/1.json
  def update
    @news = News.find(params[:id])

    respond_to do |format|
      if @news.update_attributes(params[:news])
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news = News.find(params[:id])
    @news.destroy

    respond_to do |format|
      format.html { redirect_to news_index_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.erb
<%= form_for(@news) do |f| %>
  <% if @news.errors.any? %>
	<div id="NewsErrorPosition">
		<div id="error_explanation">
			<h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>
			<ul>
				<% @news.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	</div>
  <% end %>
	<table class="newTable">
		<tr>
			<th>
				<%= f.label :title %>
			</th>
			<td>
				<%= f.text_field :title %>
			</td>
		</tr>
		<tr>
			<th>
				<%= f.label :content, "Details" %>
			</th>
			<td>
				<%= f.text_area :content, :size=>"25x15" %>
			</td>
		</tr>
		<tr>
			<td style="border-style:none">
			</td>
			<td style="text-align:right; border-style:none">
				<%= f.submit %>
			</td>
		</tr>
	</table>
<% end %>

app/views/news/edit.html.erb
<h1>Editing news</h1>

<%= render 'form' %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/news/index.html.erb
<div id="indexContent">
	<h1>Recent News</h1>
	<% @news.each do |news| %>
		<div id="indexContents">
			<div id="indexContentTitle">
				<%= link_to news.title, news_path(news) %>
			</div>
			<div id="indexContentContent">
				<%= news.content %>
				<% if isAdmin %>
					<%= link_to 'Edit', edit_news_path(news) %>
			<%= button_to 'Delete', news_path(news), :method => 'delete' %>
				<% end %>
			</div>
			<br />
		</div>
	<% end %>
	<br />
	<% if isAdmin %>
		<%= link_to 'Create', new_news_path %>
	<% end %>
</div>

app/views/news/new.html.erb
<h1>Create a piece of news:</h1>

<%= render 'form' %>

app/views/news/show.html.erb
<h1>Showing News:</h1>
<div id="indexContents">
	<div id="indexContentTitle">
		<%= link_to @news.title, news_path(@news) %>
	</div>
	<div id="indexContentContent">
		<%= @news.content %>
		<% if isAdmin %>
			<%= link_to 'Edit', edit_news_path(@news) %>
		<% end %>
	</div>
	<br />
</div>
<%= link_to 'View Other News', news_index_path %>